site_name: IzODA Documentation
pages:
  - 'About': 'index.md'
  - 'Apache Spark':
    - 'Overview': 'spark/spark.md'
    - 'Jupyter with Remote Notebook on the Mainframe': 'spark/jupyter-remote-notebook.md'
    - 'WLM Metering and Capping for IzODA Spark': 'spark/wlm-metering.md'
  - 'Optimized Data Layer / MDS':
    - 'Overview': 'odl/odl.md'
    - 'Credit Risk Assessment Example': 'odl/credit-risk-odl.md'
  - 'Anaconda':
    - 'Overview': 'anaconda/anaconda.md'
    - 'Packages': 'anaconda/packages.md'
    - 'Installation and Configuration': 'anaconda/install-config.md'
    - 'Anaconda/ODL Installation Verification with Jupyter Notebook': 'anaconda/ivp-jupyter-notebook.md'
    - 'Anaconda/ODL Installation Verification with PySpark': 'anaconda/ivp-pyspark.md'
  - 'Ecosystem': 'ecosystem.md'
extra_css: [extra.css]
extra_javascript: [index.js]
theme:
  name: readthedocs
repo_url: https://github.com/IzODA
site_description: IzODA Documentation, Guides, and Examples
site_author: Stephen Stone
copyright: Licensed/Copyrighted by IBM, 2018
